#  Copyright (C) 2022  Non-Routine LLC (contact@nonroutine.com)

#!/bin/sh -x -e
        
FILE_TEMPLATE_CONTENT=$(cat $SCRIPT_INPUT_FILE_0)
EMBEDDED_PROFILE_HASH=$(shasum -a 256 "$CODESIGNING_FOLDER_PATH/$EMBEDDED_PROFILE_NAME" | awk '{ print $1 }')
FILE_CONTENT=${FILE_TEMPLATE_CONTENT//HASH_PLACEHOLDER/"$EMBEDDED_PROFILE_HASH"}
FILE_CONTENT=${FILE_CONTENT//ID_PLACEHOLDER/"$PRODUCT_BUNDLE_IDENTIFIER"}
FILE_CONTENT=${FILE_CONTENT//COMPONENT_PLACEHOLDER/"$AUDIO_COMPONENTS_SUBTYPE"}
FILE_CONTENT=${FILE_CONTENT//EXTENSION_BUNDLE_IDENTIFIER_PLACEHOLDER/"$EXTENSION_BUNDLE_IDENTIFIER"}
FILE_CONTENT=${FILE_CONTENT//APP_GROUP_IDENTIFIER_PLACEHOLDER/"$SHARED_DATA_GROUP_ID"}
echo "$FILE_CONTENT" > $SCRIPT_OUTPUT_FILE_0
